# Generated by Django 5.0.6 on 2024-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Admin'), ('4', 'User'), ('3', 'HR'), ('2', 'HRManager')], max_length=10, null=True),
        ),
    ]
