# Generated by Django 5.0.6 on 2024-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='agenda',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='meeting_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
