# Generated by Django 5.0.6 on 2024-05-21 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('job_id', models.CharField(default='', max_length=100)),
                ('resume', models.FileField(default='', upload_to='media/')),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_id', models.IntegerField(default=0)),
                ('job_title', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
