# Generated by Django 5.0.4 on 2024-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('4', 'User'), ('3', 'HR'), ('2', 'HRManager')], default='4', max_length=10),
        ),
    ]
